<?php

namespace Katana\AffiliateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RawDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RawDataRepository extends EntityRepository
{
}
