<?php

namespace Katana\DictionaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    public function findByOffer($Offer)
    {
        $qb = $this->createQueryBuilder('device')
            ->select('device')
            ->join('device.offers', 'offer')
            ->where('offer = :offer')
            ->setParameter('offer', $Offer);

        return $qb->getQuery()->execute();
    }

    public function findInString($str)
    {
        $Devices = $this->createQueryBuilder('device')
            ->select('device')
            ->getQuery()->execute();

        foreach($Devices as $device)
        {
//echo "comparison - $str and {$device->getName()} \n";
            if ( substr_count( strtolower($str), strtolower($device->getName()) )  ){
                return $device;
            }
        }

        return null;
    }
}
