parameters:
#    katana_hasoffers.example.class: Katana\HasoffersBundle\Example


services:
#    katana_hasoffers.example:
#        class: %katana_hasoffers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    offers_update:
        class: Katana\SyncBundle\Service\OffersUpdate
        arguments: ['@service_container']

    Itunes:
        class: Katana\SyncBundle\Service\Itunes
        arguments: ['@service_container']

    PlayGoogle:
        class: Katana\SyncBundle\Service\PlayGoogle
        arguments: ['@service_container']

    CurlService:
        class: Katana\SyncBundle\Service\CurlService
        arguments: ['@service_container']

    AffiliateDataLoader:
        class: Katana\SyncBundle\Service\AffiliateDataLoader
        arguments: ['@service_container']

    OfferFactory:
        class: Katana\SyncBundle\Service\OfferFactory
        arguments: ['@service_container']

    AffiliateAuthManager:
        class: Katana\SyncBundle\Service\AffiliateAuthManager
        arguments: ['@service_container']

    RedirectUrlFinderManager:
        class: Katana\SyncBundle\Service\FinderManager\RedirectUrlFinderManager
        arguments: ['@service_container']
