<?php

namespace Katana\OfferBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends EntityRepository
{
    public function findAllApps()
    {
        $qb = $this->createQueryBuilder('app')
            ;

        return $qb->getQuery()->execute();
    }


//    public function getAllIos(){
//
//    }
}
