<?php

namespace Katana\OfferBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PayoutHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayoutHistoryRepository extends EntityRepository
{
}
